### ISSUE TITLE
Fix remaining line length issues in main.py

### ISSUE THREAD

**Issue by goldseven** [bitinerant/cleargopher#32]
The remaining line length PEP8 issues in `main.py` are within a complex shell script. This is the last remaining style issue that I'm not comfortable fixing as @bitinerant knows more about how this should work.

Once that is fixed, I think we're ready to start using [`black`](https://github.com/ambv/black) to automatically format all of the projects code and then it's mechanical how things should look and everything will pass style checks all the time.

**Comment by bitinerant** [comment]
@goldseven - There are actually 3 remaining issues here:
- [ ] Shell commands as you noted (I've already begun work on moving these out)
- [ ] Long URLs (see [commit 5d0f66d](https://github.com/bitinerant/cleargopher/commit/5d0f66d2a08dbe92f2eef59bf05a674b7e899908#commitcomment-32255593) )
- [ ] Marking which strings need translation, since `black` will convert strings to single quotes. I've been using double quotes for translatable and single quotes for non-translatable strings. I'm happy to use another system, but we need to find one that will hopefully work with whatever l10n method we end up using.

**Comment by bitinerant** [comment]
The "Marking which strings need translation" above is solved in #34.

**Comment by bitinerant** [comment]
Shell commands fixed in commit 6349733.

**Comment by bitinerant** [comment]
"Long URLs" issue resolved; see commit 5d0f66d.
